Import Libraries

In [163]:
import kagglehub
import pandas as pd
import os

# EDA

Import data

In [164]:
path = kagglehub.dataset_download("arashnic/fitbit")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\Owner\.cache\kagglehub\datasets\arashnic\fitbit\versions\2

In [165]:
data_path = r"C:\Users\Owner\.cache\kagglehub\datasets\arashnic\fitbit\versions\2\mturkfitbit_export_4.12.16-5.12.16\Fitabase Data 4.12.16-5.12.16"

In [ ]:
# 1. dailyActivity
dailyActivity = pd.read_csv(os.path.join(data_path, "dailyActivity_merged.csv"))

# 2. dailyCalories
dailyCalories = pd.read_csv(os.path.join(data_path, "dailyCalories_merged.csv"))

# 3. dailyIntensities
dailyIntensities = pd.read_csv(os.path.join(data_path, "dailyIntensities_merged.csv"))

# 4. dailySteps
dailySteps = pd.read_csv(os.path.join(data_path, "dailySteps_merged.csv"))

# 5. heartrate_seconds
heartrate_seconds = pd.read_csv(os.path.join(data_path, "heartrate_seconds_merged.csv"))

# 6. hourlyCalories
hourlyCalories = pd.read_csv(os.path.join(data_path, "hourlyCalories_merged.csv"))

# 7. hourlyIntensities
hourlyIntensities = pd.read_csv(os.path.join(data_path, "hourlyIntensities_merged.csv"))

# 8. hourlySteps
hourlySteps = pd.read_csv(os.path.join(data_path, "hourlySteps_merged.csv"))

# 9. minuteCaloriesNarrow
minuteCaloriesNarrow = pd.read_csv(os.path.join(data_path, "minuteCaloriesNarrow_merged.csv"))

# 10. minuteCaloriesWide
minuteCaloriesWide = pd.read_csv(os.path.join(data_path, "minuteCaloriesWide_merged.csv"))

# 11. minuteIntensitiesNarrow
minuteIntensitiesNarrow = pd.read_csv(os.path.join(data_path, "minuteIntensitiesNarrow_merged.csv"))

# 12. minuteIntensitiesWide
minuteIntensitiesWide = pd.read_csv(os.path.join(data_path, "minuteIntensitiesWide_merged.csv"))

# 13. minuteMETsNarrow
minuteMETsNarrow = pd.read_csv(os.path.join(data_path, "minuteMETsNarrow_merged.csv"))

# 14. minuteSleep
minuteSleep = pd.read_csv(os.path.join(data_path, "minuteSleep_merged.csv"))

# 15. minuteStepsNarrow
minuteStepsNarrow = pd.read_csv(os.path.join(data_path, "minuteStepsNarrow_merged.csv"))

# 16. minuteStepsWide
minuteStepsWide = pd.read_csv(os.path.join(data_path, "minuteStepsWide_merged.csv"))

# 17. sleepDay
sleepDay = pd.read_csv(os.path.join(data_path, "sleepDay_merged.csv"))

# 18. weightLogInfo
weightLogInfo = pd.read_csv(os.path.join(data_path, "weightLogInfo_merged.csv"))

# Explanation of the data and selection of relevant tables

### **Daily Level Data**

* **dailyActivity:** The most comprehensive daily table. It includes total steps, total distance, a breakdown of activity levels (Very, Moderately, Lightly, and Sedentary) by both minutes and distance, and total calories burned.
* **dailyCalories:** Focuses strictly on the total number of calories burned by each user per day.
* **dailyIntensities:** Provides a detailed breakdown of the time and distance spent in each intensity category per day.
* **dailySteps:** Contains only the total step count for each user per day.
* **sleepDay:** Summarizes daily sleep data, including the number of sleep records, total minutes spent asleep, and total time spent in bed.

### **Hourly Level Data**

* **hourlyCalories:** The amount of calories burned during each specific hour of the day.
* **hourlyIntensities:** Shows the total and average activity intensity for each hour.
* **hourlySteps:** The total number of steps taken during each hour.

### **Minute Level Data**

These tables come in two formats: **Narrow** (one row per minute) and **Wide** (one row per hour with 60 columns representing each minute).

* **minuteCalories (Narrow/Wide):** Calories burned tracked at a minute-by-minute granularity.
* **minuteIntensities (Narrow/Wide):** The intensity level recorded for every minute.
* **minuteSteps (Narrow/Wide):** The exact number of steps taken in every minute.
* **minuteMETsNarrow:** Displays Metabolic Equivalent of Task (MET) values per minute, which represent the energy cost of physical activities.
* **minuteSleep:** Logs the sleep state (represented by numeric values for sleep stages/wakefulness) for every minute of a sleep log.

### **Additional Logs**

* **heartrate_seconds:** High-resolution heart rate data, recorded approximately every 5 seconds.
* **weightLogInfo:** User-logged weight data, including Weight (Kg/Pounds), BMI, Body Fat (rarely populated), and whether the report was submitted manually.

# Focus Area: Primary Data Tables

Based on the initial dataset overview, I have chosen to focus my analysis on the following five tables:

1. **dailyActivity**
2. **sleepDay**
3. **hourlySteps**
4. **heartrate_seconds**
5. **weightLogInfo**

### Data cleaning

In [167]:
data_dict = {
    "dailyActivity":     dailyActivity,
    "sleepDay":          sleepDay,
    "hourlySteps":       hourlySteps,
    "heartrate_seconds": heartrate_seconds,
    "weightLogInfo":     weightLogInfo
}

In [168]:
def summarize_df(df, name):
    print("\n" + "="*40)
    print("Summary for", name)
    print("="*40)
    print("Shape:", df.shape)
    print("Columns:", list(df.columns))
    df.info()
    print(df.head())

In [169]:
def basic_clean(df, columns_list):
    print("Total duplicated rows:", df.duplicated().sum())
    print(f"Duplicated based on {columns_list}:", df.duplicated(subset=columns_list).sum())
    print("Null values per column:\n", df.isnull().sum())
    
    return df

## Clean dailyActivity df

In [170]:
summarize_df(dailyActivity, "dailyActivity")

========================================
Summary for dailyActivity
========================================
Shape: (940, 15)
Columns: ['Id', 'ActivityDate', 'TotalSteps', 'TotalDistance', 'TrackerDistance', 'LoggedActivitiesDistance', 'VeryActiveDistance', 'ModeratelyActiveDistance', 'LightActiveDistance', 'SedentaryActiveDistance', 'VeryActiveMinutes', 'FairlyActiveMinutes', 'LightlyActiveMinutes', 'SedentaryMinutes', 'Calories']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 940 entries, 0 to 939
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Id                        940 non-null    int64
 1   ActivityDate              940 non-null    object
 2   TotalSteps                940 non-null    int64
 3   TotalDistance             940 non-null    float64
 4   TrackerDistance           940 non-null    float64
 5   LoggedActivitiesDistance  940 non-null    float64
 6   VeryActiveDistance        940 non-null    float64
 7   ModeratelyActiveDistance  940 non-null    float64
 8   LightActiveDistance       940 non-null    float64
 9   SedentaryActiveDistance   940 non-null    float64
 10  VeryActiveMinutes         940 non-null    int64
 11  FairlyActiveMinutes       940 non-null    int64
 12  LightlyActiveMinutes      940 non-null    int64
 13  SedentaryMinutes          940 non-null    int64
 14  Calories                  940 non-null    int64
dtypes: float64(7), int64(7), object(1)
memory usage: 110.3+ KB
           Id ActivityDate  TotalSteps  TotalDistance  TrackerDistance  \
0  1503960366    4/12/2016       13162           8.50             8.50
1  1503960366    4/13/2016       10735           6.97             6.97
2  1503960366    4/14/2016       10460           6.74             6.74
3  1503960366    4/15/2016        9762           6.28             6.28
4  1503960366    4/16/2016       12669           8.16             8.16

   LoggedActivitiesDistance  VeryActiveDistance  ModeratelyActiveDistance  \
0                       0.0                1.88                      0.55
1                       0.0                1.57                      0.69
2                       0.0                2.44                      0.40
3                       0.0                2.14                      1.26
4                       0.0                2.71                      0.41

   LightActiveDistance  SedentaryActiveDistance  VeryActiveMinutes  \
0                 6.06                      0.0                 25
1                 4.71                      0.0                 21
2                 3.91                      0.0                 30
3                 2.83                      0.0                 29
4                 5.04                      0.0                 36

   FairlyActiveMinutes  LightlyActiveMinutes  SedentaryMinutes  Calories
0                   13                   328               728      1985
1                   19                   217               776      1797
2                   11                   181              1218      1776
3                   34                   209               726      1745
4                   10                   221               773      1863

In [171]:
basic_clean(dailyActivity, ["Id", "ActivityDate"])

Total duplicated rows: 0
Duplicated based on ['Id', 'ActivityDate']: 0
Null values per column:
 Id                          0
ActivityDate                0
TotalSteps                  0
TotalDistance               0
TrackerDistance             0
LoggedActivitiesDistance    0
VeryActiveDistance          0
ModeratelyActiveDistance    0
LightActiveDistance         0
SedentaryActiveDistance     0
VeryActiveMinutes           0
FairlyActiveMinutes         0
LightlyActiveMinutes        0
SedentaryMinutes            0
Calories                    0
dtype: int64

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
0,1503960366,4/12/2016,13162,8.500000,8.500000,0.0,1.88,0.55,6.06,0.00,25,13,328,728,1985
1,1503960366,4/13/2016,10735,6.970000,6.970000,0.0,1.57,0.69,4.71,0.00,21,19,217,776,1797
2,1503960366,4/14/2016,10460,6.740000,6.740000,0.0,2.44,0.40,3.91,0.00,30,11,181,1218,1776
3,1503960366,4/15/2016,9762,6.280000,6.280000,0.0,2.14,1.26,2.83,0.00,29,34,209,726,1745
4,1503960366,4/16/2016,12669,8.160000,8.160000,0.0,2.71,0.41,5.04,0.00,36,10,221,773,1863
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
935,8877689391,5/8/2016,10686,8.110000,8.110000,0.0,1.08,0.20,6.80,0.00,17,4,245,1174,2847
936,8877689391,5/9/2016,20226,18.250000,18.250000,0.0,11.10,0.80,6.24,0.05,73,19,217,1131,3710
937,8877689391,5/10/2016,10733,8.150000,8.150000,0.0,1.35,0.46,6.28,0.00,18,11,224,1187,2832
938,8877689391,5/11/2016,21420,19.559999,19.559999,0.0,13.22,0.41,5.89,0.00,88,12,213,1127,3832
939,8877689391,5/12/2016,8064,6.120000,6.120000,0.0,1.82,0.04,4.25,0.00,23,1,137,770,1849

In [172]:
dailyActivity["ActivityDate"] = pd.to_datetime(dailyActivity["ActivityDate"])
print(dailyActivity["ActivityDate"].dtype)

datetime64[ns]

In [173]:
dailyActivity = dailyActivity.rename(columns={
    "Id": "user_id",
    "ActivityDate": "activity_date",
    "TotalSteps": "total_steps",
    "Calories": "calories"
})

In [174]:
dailyActivity[dailyActivity["total_steps"] == 0]

,user_id,activity_date,total_steps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,calories
30,1503960366,2016-05-12,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,1440,0
104,1844505072,2016-04-24,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,1440,1347
105,1844505072,2016-04-25,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,1440,1347
106,1844505072,2016-04-26,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,1440,1347
112,1844505072,2016-05-02,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,1440,1348
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
904,8792009665,2016-05-06,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,1440,1688
905,8792009665,2016-05-07,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,1440,1688
906,8792009665,2016-05-08,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,1440,1688
907,8792009665,2016-05-09,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,1440,1688
908,8792009665,2016-05-10,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,48,57

In [175]:
dailyActivity[dailyActivity["calories"] == 0]

,user_id,activity_date,total_steps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,calories
30,1503960366,2016-05-12,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,1440,0
653,6290855005,2016-05-10,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,1440,0
817,8253242879,2016-04-30,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,1440,0
879,8583815059,2016-05-12,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,1440,0

Mark rows with zero steps or calories as incomplete or potentially missing data
This helps to track data quality without deleting any records

In [176]:
dailyActivity['incomplete'] = (dailyActivity['total_steps'] == 0) | (dailyActivity['calories'] == 0)

In [ ]:
dailyActivity["calories_per_step"] = dailyActivity["Calories"] / dailyActivity["TotalSteps"]

In [177]:
dailyActivity.to_csv("clean_daily_activity.csv", index=False)

## Clean sleepDay Df

In [178]:
summarize_df(sleepDay, "sleepDay")

========================================
Summary for sleepDay
========================================
Shape: (413, 5)
Columns: ['Id', 'SleepDay', 'TotalSleepRecords', 'TotalMinutesAsleep', 'TotalTimeInBed']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 413 entries, 0 to 412
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Id                  413 non-null    int64
 1   SleepDay            413 non-null    object
 2   TotalSleepRecords   413 non-null    int64
 3   TotalMinutesAsleep  413 non-null    int64
 4   TotalTimeInBed      413 non-null    int64
dtypes: int64(4), object(1)
memory usage: 16.3+ KB
           Id               SleepDay  TotalSleepRecords  TotalMinutesAsleep  \
0  1503960366  4/12/2016 12:00:00 AM                  1                 327
1  1503960366  4/13/2016 12:00:00 AM                  2                 384
2  1503960366  4/15/2016 12:00:00 AM                  1                 412
3  1503960366  4/16/2016 12:00:00 AM                  2                 340
4  1503960366  4/17/2016 12:00:00 AM                  1                 700

   TotalTimeInBed
0             346
1             407
2             442
3             367
4             712

In [179]:
basic_clean(sleepDay, ["Id", "SleepDay"])

Total duplicated rows: 3
Duplicated based on ['Id', 'SleepDay']: 3
Null values per column:
 Id                    0
SleepDay              0
TotalSleepRecords     0
TotalMinutesAsleep    0
TotalTimeInBed        0
dtype: int64

,Id,SleepDay,TotalSleepRecords,TotalMinutesAsleep,TotalTimeInBed
0,1503960366,4/12/2016 12:00:00 AM,1,327,346
1,1503960366,4/13/2016 12:00:00 AM,2,384,407
2,1503960366,4/15/2016 12:00:00 AM,1,412,442
3,1503960366,4/16/2016 12:00:00 AM,2,340,367
4,1503960366,4/17/2016 12:00:00 AM,1,700,712
...,...,...,...,...,...
408,8792009665,4/30/2016 12:00:00 AM,1,343,360
409,8792009665,5/1/2016 12:00:00 AM,1,503,527
410,8792009665,5/2/2016 12:00:00 AM,1,415,423
411,8792009665,5/3/2016 12:00:00 AM,1,516,545
412,8792009665,5/4/2016 12:00:00 AM,1,439,463

In [180]:
sleepDay = sleepDay.drop_duplicates(subset=["Id","SleepDay"])

In [181]:
sleepDay = sleepDay.copy()
sleepDay.loc[:, "SleepDay"] = pd.to_datetime(
    sleepDay["SleepDay"],
    format="%m/%d/%Y %I:%M:%S %p",
    errors='coerce'
)

print(sleepDay["SleepDay"].dtype)
print(sleepDay[sleepDay["SleepDay"].isna()]) 
print(type(sleepDay["SleepDay"].iloc[0]))

object
Empty DataFrame
Columns: [Id, SleepDay, TotalSleepRecords, TotalMinutesAsleep, TotalTimeInBed]
Index: []
<class 'pandas._libs.tslibs.timestamps.Timestamp'>

In [182]:
sleepDay = sleepDay.rename(columns={
    "Id": "user_id",
    "SleepDay": "sleep_date",
    "TotalSleepRecords": "total_sleep_records",
    "TotalMinutesAsleep": "minutes_asleep",
    "TotalTimeInBed": "minutes_in_bed"
})

In [183]:
sleepDay['minutes_awake_in_bed'] = sleepDay['minutes_in_bed'] - sleepDay['minutes_asleep']

In [184]:
sleepDay['incomplete'] = (sleepDay['minutes_asleep'] == 0) | (sleepDay['minutes_in_bed'] == 0)

In [185]:
sleepDay.to_csv("clean_sleep_day.csv", index=False)

## Clean hourlySteps Df

In [186]:
summarize_df(hourlySteps, "hourlySteps")

========================================
Summary for hourlySteps
========================================
Shape: (22099, 3)
Columns: ['Id', 'ActivityHour', 'StepTotal']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22099 entries, 0 to 22098
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            22099 non-null  int64
 1   ActivityHour  22099 non-null  object
 2   StepTotal     22099 non-null  int64
dtypes: int64(2), object(1)
memory usage: 518.1+ KB
           Id           ActivityHour  StepTotal
0  1503960366  4/12/2016 12:00:00 AM        373
1  1503960366   4/12/2016 1:00:00 AM        160
2  1503960366   4/12/2016 2:00:00 AM        151
3  1503960366   4/12/2016 3:00:00 AM          0
4  1503960366   4/12/2016 4:00:00 AM          0

In [187]:
basic_clean(hourlySteps, ["Id", "ActivityHour"])

Total duplicated rows: 0
Duplicated based on ['Id', 'ActivityHour']: 0
Null values per column:
 Id              0
ActivityHour    0
StepTotal       0
dtype: int64

               Id           ActivityHour  StepTotal
0      1503960366  4/12/2016 12:00:00 AM        373
1      1503960366   4/12/2016 1:00:00 AM        160
2      1503960366   4/12/2016 2:00:00 AM        151
3      1503960366   4/12/2016 3:00:00 AM          0
4      1503960366   4/12/2016 4:00:00 AM          0
...           ...                    ...        ...
22094  8877689391  5/12/2016 10:00:00 AM        514
22095  8877689391  5/12/2016 11:00:00 AM       1407
22096  8877689391  5/12/2016 12:00:00 PM       3135
22097  8877689391   5/12/2016 1:00:00 PM        307
22098  8877689391   5/12/2016 2:00:00 PM        457

[22099 rows x 3 columns]

In [188]:
hourlySteps['ActivityHour'] = pd.to_datetime(
    hourlySteps['ActivityHour'], 
    format="%m/%d/%Y %I:%M:%S %p", 
    errors='coerce'
)
print(hourlySteps["ActivityHour"].dtype)

datetime64[ns]

In [189]:
hourlySteps = hourlySteps.rename(columns={
    "Id": "user_id",
    "ActivityHour": "activity_hour",
    "StepTotal": "steps"
})

In [191]:
hourlySteps['hour'] = hourlySteps['activity_hour'].dt.hour
hourlySteps['day'] = hourlySteps['activity_hour'].dt.date

In [192]:
hourlySteps.to_csv("clean_hourly_steps.csv", index=False)

## Clean heartrate_seconds Df

In [193]:
summarize_df(heartrate_seconds, "heartrate_seconds")

========================================
Summary for heartrate_seconds
========================================
Shape: (2483658, 4)
Columns: ['Id', 'Time', 'Value', 'flag']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2483658 entries, 0 to 2483657
Data columns (total 4 columns):
 #   Column  Dtype
---  ------  -----
 0   Id      int64
 1   Time    object
 2   Value   int64
 3   flag    bool
dtypes: bool(1), int64(2), object(1)
memory usage: 59.2+ MB
           Id                  Time  Value   flag
0  2022484408  4/12/2016 7:21:00 AM     97  False
1  2022484408  4/12/2016 7:21:05 AM    102  False
2  2022484408  4/12/2016 7:21:10 AM    105  False
3  2022484408  4/12/2016 7:21:20 AM    103  False
4  2022484408  4/12/2016 7:21:25 AM    101  False

In [194]:
basic_clean(heartrate_seconds, ["Id", "Time"])

Total duplicated rows: 0
Duplicated based on ['Id', 'Time']: 0
Null values per column:
 Id       0
Time     0
Value    0
flag     0
dtype: int64

                 Id                  Time  Value   flag
0        2022484408  4/12/2016 7:21:00 AM     97  False
1        2022484408  4/12/2016 7:21:05 AM    102  False
2        2022484408  4/12/2016 7:21:10 AM    105  False
3        2022484408  4/12/2016 7:21:20 AM    103  False
4        2022484408  4/12/2016 7:21:25 AM    101  False
...             ...                   ...    ...    ...
2483653  8877689391  5/12/2016 2:43:53 PM     57  False
2483654  8877689391  5/12/2016 2:43:58 PM     56  False
2483655  8877689391  5/12/2016 2:44:03 PM     55  False
2483656  8877689391  5/12/2016 2:44:18 PM     55  False
2483657  8877689391  5/12/2016 2:44:28 PM     56  False

[2483658 rows x 4 columns]

In [195]:
heartrate_seconds['Time'] = pd.to_datetime(
    heartrate_seconds['Time'], 
    format="%m/%d/%Y %I:%M:%S %p", 
    errors='coerce'
)
print(heartrate_seconds["Time"].dtype)

datetime64[ns]

In [ ]:
heartrate_seconds['flag'] = (heartrate_seconds['Value'] == 0) | (heartrate_seconds['Value'] < 40) | (heartrate_seconds['Value'] > 200)

In [196]:
heartrate_seconds['incomplete'] = (heartrate_seconds['Value'] == 0)

In [197]:
heartrate_seconds = heartrate_seconds.rename(columns={
    'ID': 'user_id',
    'Time': 'timestamp',
    'Value': 'heartrate'
})

In [198]:
heartrate_seconds.to_csv("heartrate_seconds_clean.csv", index=False)

## Clean weightLogInfo Df

In [199]:
summarize_df(weightLogInfo, "weightLogInfo")

========================================
Summary for weightLogInfo
========================================
Shape: (67, 8)
Columns: ['Id', 'Date', 'WeightKg', 'WeightPounds', 'Fat', 'BMI', 'IsManualReport', 'LogId']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Id              67 non-null     int64
 1   Date            67 non-null     object
 2   WeightKg        67 non-null     float64
 3   WeightPounds    67 non-null     float64
 4   Fat             2 non-null      float64
 5   BMI             67 non-null     float64
 6   IsManualReport  67 non-null     bool
 7   LogId           67 non-null     int64
dtypes: bool(1), float64(4), int64(2), object(1)
memory usage: 3.9+ KB
           Id                   Date    WeightKg  WeightPounds   Fat  \
0  1503960366   5/2/2016 11:59:59 PM   52.599998    115.963147  22.0
1  1503960366   5/3/2016 11:59:59 PM   52.599998    115.963147   NaN
2  1927972279   4/13/2016 1:08:52 AM  133.500000    294.317120   NaN
3  2873212765  4/21/2016 11:59:59 PM   56.700001    125.002104   NaN
4  2873212765  5/12/2016 11:59:59 PM   57.299999    126.324875   NaN

         BMI  IsManualReport          LogId
0  22.650000            True  1462233599000
1  22.650000            True  1462319999000
2  47.540001           False  1460509732000
3  21.450001            True  1461283199000
4  21.690001            True  1463097599000

In [200]:
basic_clean(weightLogInfo, ["Id", "Date"])

Total duplicated rows: 0
Duplicated based on ['Id', 'Date']: 0
Null values per column:
 Id                 0
Date               0
WeightKg           0
WeightPounds       0
Fat               65
BMI                0
IsManualReport     0
LogId              0
dtype: int64

,Id,Date,WeightKg,WeightPounds,Fat,BMI,IsManualReport,LogId
0,1503960366,5/2/2016 11:59:59 PM,52.599998,115.963147,22.0,22.650000,True,1462233599000
1,1503960366,5/3/2016 11:59:59 PM,52.599998,115.963147,NaN,22.650000,True,1462319999000
2,1927972279,4/13/2016 1:08:52 AM,133.500000,294.317120,NaN,47.540001,False,1460509732000
3,2873212765,4/21/2016 11:59:59 PM,56.700001,125.002104,NaN,21.450001,True,1461283199000
4,2873212765,5/12/2016 11:59:59 PM,57.299999,126.324875,NaN,21.690001,True,1463097599000
...,...,...,...,...,...,...,...,...
62,8877689391,5/6/2016 6:43:35 AM,85.000000,187.392923,NaN,25.440001,False,1462517015000
63,8877689391,5/8/2016 7:35:53 AM,85.400002,188.274775,NaN,25.559999,False,1462692953000
64,8877689391,5/9/2016 6:39:44 AM,85.500000,188.495234,NaN,25.610001,False,1462775984000
65,8877689391,5/11/2016 6:51:47 AM,85.400002,188.274775,NaN,25.559999,False,1462949507000
66,8877689391,5/12/2016 6:42:53 AM,84.000000,185.188300,NaN,25.139999,False,1463035373000

In [201]:
# The 'Fat' column contains 65 missing values out of 67 rows in the dataset.
# Because most of the values are missing, the column provides very little useful information for analysis and could introduce noise or bias.
# Therefore, I remove it from the dataset.
weightLogInfo = weightLogInfo.drop(columns=["Fat"])

In [202]:
# 'WeightPounds' represents the same information as 'WeightKg' but in a different unit. 
# Since 'WeightKg' is already available, keeping both columns is redundant, so we remove 'WeightPounds'.
weightLogInfo = weightLogInfo.drop(columns=["WeightPounds"])

In [203]:
weightLogInfo['Date'] = pd.to_datetime(
    weightLogInfo['Date'], 
    format="%m/%d/%Y %I:%M:%S %p", 
    errors='coerce'
)
print(weightLogInfo["Date"].dtype)

datetime64[ns]

In [204]:
weightLogInfo['missing_weight'] = (weightLogInfo['WeightKg'] == 0)

In [205]:
weightLogInfo = weightLogInfo.rename(columns={
    'Id': 'user_id',
    'Date': 'date',
    'WeightKg': 'weight_kg',
    'BMI': 'bmi',
    'IsManualReport': 'manual_report',
    'LogId': 'log_id'
})

In [206]:
weightLogInfo.to_csv("weightLogInfo_clean.csv", index=False)

## Loading Clean Data into MySQL

After cleaning the Fitbit datasets, the next step was to load the data into a relational database (MySQL).

Separate tables were created for:
- daily_activity
- hourly_steps
- heartrate_seconds
- sleep
- weight_log

The cleaned CSV files were then loaded into the database using Python and SQL.